### ISSUE TITLE
figures not displaying

### ISSUE THREAD

**Issue by divvi12** [grenagit/MMM-MarineWeather#1]
I have added the module to my MM, and although the values are displayng correctly, the figures(referring to the water droplet etc.) is missing. Do you have any suggestions?
Code in config:
{
  		module: "MMM-MarineWeather",
		position: "top_right",
		config: {
			latitude: 34.1062, // Latitude 
			longitude: 18.8176, // Longitude
			appid: "xxxxxxx",
			showWavePeriod: false
		}
		
		},	
![display](https://user-images.githubusercontent.com/50736764/64918640-522e8e00-d7a1-11e9-95fb-cc9656a92320.PNG)

**Comment by grenagit** [comment]
Figures display uses *FontAwesome* which is normally **included** in the *MagicMirror core* !

**Please check that :**
 - the Fontawesome CSS file `font-awesome.css` is present on your MagicMirror: `ls -la ~/MagicMirror/vendor/css/`
 - the FontAwesome NodeJS module `@fortawesome/fontawesome-free` is installed on your MagicMirror: `cd ~/MagicMirror/vendor/node_modules/ && npm list | grep @fortawesome/fontawesome-free`

**Comment by divvi12** [comment]
Both are present, could there be a different reason?
