### ISSUE TITLE
No title for module display?

### ISSUE THREAD

**Issue by dbg62** [grenagit/MMM-MarineWeather#6]
Hi

Thanks for the module!

Just installed it, everything works fine, apart from the 'Current Marine Weather' onscreen title?

Seems to be missing? I tried the install at various positions and still the same?

Regards

**Comment by grenagit** [comment]
Hello,

To display a title (here "Current Marine Weather"), simply use the `header` option into `config/config.js` file !

*To get this:*

![MMM-MarineWeather Screenshot #1](https://github.com/grenagit/MMM-MarineWeather/raw/master/MMM-MarineWeather_screenshot1.png)

*You must configure the module by following this example (note `header: "Current Marine Weather",`):*
```js
modules: [
	{
		module: "MMM-MarineWeather",
		position: "top_right",
		header: "Current Marine Weather",
		config: {
			latitude: 0, // Latitude 
			longitude: 0, // Longitude
			appid: "abcde12345abcde12345abcde12345ab" // StormGlass API key (docs.stormglass.io)
		}
	}
]
```

More information into MagicMirror² Documentation: [Module Configuration](https://docs.magicmirror.builders/modules/configuration.html#example)

**Comment by dbg62** [comment]
Thank you!
